// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgmbqfpvdmzeubacuung.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnbWJxZnB2ZG16ZXViYWN1dW5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NDA4NjYsImV4cCI6MjA1ODUxNjg2Nn0._Ijsa55NyKccAG6b3d9KR-TnLD4uV0DiFsn4ZAPBykk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);